project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - teaching_finance_with_ai_logo.png

site:
  title: ""
  site-url: https://finance-with-ai.org
  description: "Teaching the use of generative AI in finance"
  navbar:
    logo: "teaching_finance_with_ai_logo.png"
    right:
      - icon: substack
        href: https://kerryback.substack.com
      - icon: journal-text
        href: https://blog.kerryback.com
      - icon: mortarboard
        href: https://mgmt675-2026.kerryback.com/syllabus.pdf
        target: _blank

format:
  html:
    theme:
      light: flatly
      dark: superhero
    css: styles.css
    toc: true
