project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - teaching_finance_with_ai_logo.png
    - image1.png
    - image2.png

site:
  title: ""
  site-url: https://finance-with-ai.org
  description: "Teaching the use of generative AI in finance"

format:
  html:
    theme:
      light: flatly
      dark: superhero
    css: styles.css
    toc: true

comments:
  giscus:
    repo: kerryback/finance-and-ai
    # repo-id: UPDATE_THIS_FROM_GISCUS_APP
    # category: General
    # category-id: UPDATE_THIS_FROM_GISCUS_APP
    mapping: pathname
    reactions-enabled: true
    loading: lazy
    input-position: bottom
    theme: preferred_color_scheme 
